---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kepler
  name: otelcol
  labels:
    otel: collect
data:
  otelconfig.yaml: |
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'kepler'
            scrape_interval: 2s
            static_configs:
            - targets: ['localhost:9102'] # application metrics endpoint
    processors:
      memory_limiter:
        check_interval: 2s
        limit_percentage: 95
        spike_limit_percentage: 25
      batch:
    exporters:
       logging:
          loglevel: info

       otlp:
        endpoint: http://otel-kepler-backend.apps.zagaopenshift.zagaopensource.com:9111
        tls:
         insecure: true

    service:
      telemetry:
        logs:
          level: info
      #extensions: [bearertokenauth, basicauth/client]
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch, memory_limiter]
          exporters: [logging, otlp]
