kind: Grafana
apiVersion: grafana.integreatly.org/v1beta1
metadata:
  labels:
    dashboards: grafana-kepler
    app: grafana-kepler
  name: grafana-kepler
  namespace: kepler-demo
spec:
  deployment:
    spec:
      template:
         spec:
           containers: 
             - name: grafana
               image: >-
                 quay.io/zagaos/zaga-grafana-custom:latest
               args: 
                - '-config=/etc/grafana/grafana.ini'
  ingress:
    enabled: true
  config:
    auth:
      disable_signout_menu: 'true'
    auth.anonymous:
      enabled: 'true'
    log:
      level: warn
      mode: console
    security:
      admin_password: rhel
      admin_user: rhel
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana-kepler
